sudo: false

language: node_js

node_js:
  - '10'
  - '11'
  - '12'
  - '13'
  - '14'

branches:
  only:
    - master
    - travis

before_install:
  - npm update

install:
  - npm install

script:
  - npm run test
